services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: pwd
      POSTGRES_DATABASE: iam.db
    ports:
      - "5432:5432"
    volumes:
      - psqlvol:/var/lib/postgresql

volumes:
  psqlvol:
